name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install dependencies
      run: |
        uv sync
        source .venv/bin/activate

    - name: Start mock server
      run: |
        cd mock_server/api_server
        source ../../.venv/bin/activate
        uv run base/flask_service.py &
        sleep 5  # 等待服务器启动

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        source .venv/bin/activate
        python run.py

    - name: Upload Allure-HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: report/allure/html/

#    - name: Upload TM Report
#      uses: actions/upload-artifact@v4
#      with:
#        name: tm-report
#        path: ./report/tmreport/testReport.html
